name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copier code Git vers serveur Ubuntu
        uses: actions/checkout@v3
      - name: Installer nodeJS
        uses: actions/setup-node@v3
      - name: Installation des packages JS
        run: npm install
      - name: Build application JS
        run: npm run build
        
